baijiaxing/app/urls.py
from django.conf.urls import url

from app import views as app_views
urlpatterns = [
    url(r'^index/',app_views.get_all,name='index'),
    url(r'^get_one_xingshi/(?P<xingshi_id>\d+)',app_views.get_one_xingshi,name='get_one_xingshi'),
    url(r'^get_one_info/(?P<xingming_id>\d+)',app_views.get_one_info,name='get_one_info'),
    url(r'^add_one_xingming',app_views.add_one_xingming,name='add_one_xingming')
]

baijiaxing/baijiaxing/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('app.urls',namespace='app')),
]

baijiaxing/app/models.py
from django.db import models

# Create your models here.

class Baijiaxing(models.Model):
    id = models.IntegerField(primary_key=True)
    xingshi = models.CharField(max_length=256)
    href = models.CharField(max_length=1024)
    xingshi_zhongwen = models.CharField(max_length=256)

    class Meta:
        db_table = "baijiaxing"

class Xingming(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    the_same_people_number = models.CharField(max_length=256)
    boy_ratio = models.CharField(max_length=256)
    girl_ratio = models.CharField(max_length=256)
    five_elements = models.CharField(max_length=256)
    three_talents = models.CharField(max_length=256)
    xingshi = models.ForeignKey(Baijiaxing)

    class Meta:
        db_table = 'xingming'

baijiaxing/app/views.py
import json

import pinyin
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from app.models import Baijiaxing, Xingming


#获取所有的姓氏
def get_all(request):
    xingshi_lists = Baijiaxing.objects.all()
    the_max_leng = len(xingshi_lists)
    the_xingshi_list = []
    for i in range(0,len(list(xingshi_lists)),6):
        the_list = []
        for m in range(i,i+6):
            if m < the_max_leng:
                the_list.append(xingshi_lists[m])
        the_xingshi_list.append(the_list)
    return render(request,'index.html',{'the_xingshi_list':the_xingshi_list})


#获取每个姓氏的所有姓名并且进行分页
def get_one_xingshi(request,xingshi_id):
    try:
        xingshi = Baijiaxing.objects.filter(id=xingshi_id)[0]

        content = Xingming.objects.filter(xingshi_id = int(xingshi_id)).order_by('id')
        page_num = int(request.GET.get('page',1))
        paginator = Paginator(content,70)
        page = paginator.page(page_num)
        if not content:
            msg = '暂无此姓氏名字，快点击右上角添加吧'
        else:
            msg = ''
        return render(request,'components.html',{'page':page,'xingshi':xingshi,'msg':msg})
    except:
        return HttpResponse('暂无数据')

#获取每个姓名的信息
def get_one_info(request,xingming_id):
    try:
        the_info = Xingming.objects.filter(id = int(xingming_id))[0]
        return render(request,'tutorial.html',{'the_info':the_info})
    except:
        return HttpResponse('暂无数据')

#添加姓名
def add_one_xingming(request):
    if request.method == 'GET':
        return render(request,'landing.html')
    if request.method == 'POST':
        #获取传回来的数据
        xingshi = request.POST.get('xingshi')
        xingming = request.POST.get('xingming')
        five_elements = request.POST.get('five_elements')
        three_talents = request.POST.get('three_talents')
        #判断是否是真的没有这个姓名
        the_name = Xingming.objects.filter(name=xingming)
        if not the_name:
            #查询数据库中是否有该形式，有 只在姓名表上添加，没有 要在百家姓和姓名表都添加
            if not Baijiaxing.objects.filter(xingshi_zhongwen=xingshi):
                #没有这个姓氏
                #将姓氏转换为pinyin+数字  数字代表拼音
                the_xingshi = pinyin.get(xingshi, format='numerical', delimiter=" ")
                Baijiaxing.objects.create(xingshi=the_xingshi,xingshi_zhongwen=xingshi)
            the_xingshi_id = Baijiaxing.objects.filter(xingshi_zhongwen=xingshi).first().id
            Xingming.objects.create(name=xingming,five_elements=five_elements,three_talents=three_talents,xingshi_id=the_xingshi_id)
            return HttpResponseRedirect(reverse('app:index'))
        else:
            the_xingming = the_name.first()
            msg = '该姓名已经存在'
            return render(request,'landing.html',{'the_xingming':the_xingming,'msg':msg})

baijiaxing/templates/components.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" type="image/png" href="/static/assets/paper_img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>你的名字</title>

    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

    <link href="{% static 'bootstrap3/css/bootstrap.css' %}" rel="stylesheet"/>
    <link href="/static/assets/css/ct-paper.css" rel="stylesheet"/>
    <link href="/static/assets/css/demo.css" rel="stylesheet"/>


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

</head>
<body>

<nav class="navbar navbar-ct-danger" role="navigation-demo" id="demo-navbar">
    <div class="container">

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navigation-example-2">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'app:index' %}" class="btn btn-danger">首页</a>
                </li>
                <li>
                    <a href="{% url 'app:add_one_xingming' %}" class="btn btn-danger">你的名字</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-->
</nav>

<div class="wrapper">
    <div class="demo-header">
        <div class="motto">
            <h1 class="title-uppercase">{{ xingshi.xingshi_zhongwen }}姓名字</h1>
        </div>
    </div>
    <div class="main">
        <div class="section section-nude">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-1">
                        <div class="tim-container" style="min-height: 500px;">

                            <!-- buttons row -->
                            <div class="tim-row" id="buttons-row">

                                <h2>君の名は</h2>
                                <div id="buttons">
                                    <br/>
                                    <div class="row">
                                        <h1>{{ msg }}</h1>
                                        {% for i in page %}
                                            <a href="{% url 'app:get_one_info' i.id %} ">
                                                <button class="btn btn-fill btn-danger"
                                                        style='font-size:30px;margin:8px'>{{ i.name }}</button>
                                            </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="tim-row" id="pagination-row" align="center">
    <ul class="pagination pagination-danger">
        {% if page.has_previous %}
            <li><a href="{% url 'app:get_one_xingshi' xingshi.id %}?page={{ page.previous_page_number }}">上一页</a></li>
        {% endif %}
        {% for i in page.paginator.page_range %}
            <li><a style='font-size:20px;' href="{% url 'app:get_one_xingshi' xingshi.id %}?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        {% if page.has_next %}
            <li><a href="{% url  'app:get_one_xingshi' xingshi.id %}?page={{ page.next_page_number }}">下一页</a></li>
        {% endif %}
    </ul>
</div>
<div class="row sharing-area text-center">
    <h4><a href="http://www.fizzyi.com">欢迎来我的博客或者Github</a></h4>
    <a href="https://github.com/Fizzyi" class="btn">
        <i class="fa fa-github-square"></i>
        Github
    </a>
    <a href="http://www.fizzyi.com" class="btn">
        <i class="fa fa-rss-square"></i>
        Fizzyi
    </a>
</div>
</body>
<script src="/static/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="/static/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script src="/static/bootstrap3/js/bootstrap.js" type="text/javascript"></script>

<!--  Plugins -->
<script src="/static/assets/js/ct-paper-checkbox.js"></script>
<script src="/static/assets/js/ct-paper-radio.js"></script>
<script src="/static/assets/js/bootstrap-select.js"></script>
<script src="/static/assets/js/bootstrap-datepicker.js"></script>

<script src="/static/assets/js/ct-paper.js"></script>
<script>

    $("#slider-range").slider({
        range: true,
        min: 0,
        max: 500,
        values: [75, 300],
    });
    $("#slider-default").slider({
        value: 70,
        orientation: "horizontal",
        range: "min",
        animate: true
    });
    $('.btn-tooltip').tooltip('show');
    $('.radio').on('toggle', function () {
    });

</script>
</html>

baijiaxing/templates/index.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" type="image/png" href="/static/assets/paper_img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>你的名字 君の名は</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
    <meta name="viewport" content="width=device-width"/>

    <link href="/static/bootstrap3/css/bootstrap.css" rel="stylesheet"/>
    <link href="/static/assets/css/ct-paper.css" rel="stylesheet"/>
    <link href="/static/assets/css/demo.css" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

</head>
<body>
<nav class="navbar navbar-ct-transparent" role="navigation-demo" id="demo-navbar">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
{#        <div class="navbar-header">#}
{#            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">#}
{#                <span class="sr-only">Toggle navigation</span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
{#        </div>#}

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navigation-example-2">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'app:index' %}" class="btn btn-danger">首页</a>
                </li>
                <li>
                    <a href="{% url 'app:add_one_xingming' %}" class="btn btn-danger">你的名字</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-->
</nav>


<div class="wrapper">
    <div class="demo-header demo-header-image">
        <div class="motto">
{#            <h1 class="title-uppercase">君の名は</h1>#}
{#            <h3>寻找你的名字....</h3>#}
        </div>
    </div>

    <div class="main">
        <div class="section">
            <div class="container tim-container">
                <div class="tim-title">
                    <h2>寻找你的姓</h2>
                </div>
                <div id="buttons">
                    <br/>
                    <div class="row">
                        {% for i in the_xingshi_list %}

                            <div class="col-md-8 col-md-offset-2">
                            {% for m in i %}

                                <a href="{% url 'app:get_one_xingshi' m.id %}"><button class="btn btn-fill btn-danger" style='font-size:30px;margin:8px'>{{ m.xingshi_zhongwen }}</button></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
{#                            <button href="#fakelink" class="btn btn-fill btn-primary">Primary</button>#}
{#                            <button href="#fakelink" class="btn btn-fill btn-info">Info</button>#}
{#                            <button href="#fakelink" class="btn btn-fill btn-success">Success</button>#}
{#                            <button href="#fakelink" class="btn btn-fill btn-warning">Warning</button>#}
{#                            <button href="#fakelink" class="btn btn-fill btn-danger">Danger</button>#}
{#                            <button href="#fakelink" class="btn btn-fill btn-neutral">Neutral</button>#}
                            {% endfor %}
                            </div>
                            <br><br><br>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- </div> -->
    <div class="main">
        <div class="section section-nude section-with-space">
            <div class="container tim-container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2 text-center">
                        <h2>没找到你的名字?</h2>
                        <p>赶快将你的名字添加到我们的名字库，让所有人都能看到你的名字多么特别</p>
                    </div>
                    <div class="col-xs-8 col-xs-offset-2 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 download-area">
                        <a href="#/product/paper-kit" class="btn btn-danger btn-fill btn-block btn-lg">添加</a>
                    </div>
                </div>
                <div class="row sharing-area text-center">
                    <h4><a href="http://www.fizzyi.com">欢迎来我的博客或者Github</a></h4>
                    <a href="https://github.com/Fizzyi" class="btn">
                        <i class="fa fa-github-square"></i>
                        Github
                    </a>
                    <a href="http://www.fizzyi.com" class="btn">
                        <i class="fa fa-rss-square"></i>
                        Fizzyi
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

<script src="/static/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="/static/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script src="/static/bootstrap3/js/bootstrap.js" type="text/javascript"></script>

<!--  Plugins -->
<script src="/static/assets/js/ct-paper-checkbox.js"></script>
<script src="/static/assets/js/ct-paper-radio.js"></script>
<script src="/static/assets/js/bootstrap-select.js"></script>
<script src="/static/assets/js/bootstrap-datepicker.js"></script>

<script src="/static/assets/js/ct-paper.js"></script>
</html>

baijiaxing/templates/landing.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <link rel="icon" type="image/png" href="/static/assets/paper_img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>你的名字 君の名は</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
    <meta name="viewport" content="width=device-width"/>

    <link href="/static/bootstrap3/css/bootstrap.css" rel="stylesheet"/>
    <link href="/static/assets/css/ct-paper.css" rel="stylesheet"/>
    <link href="/static/assets/css/demo.css" rel="stylesheet"/>

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

</head>
<body>
<nav class="navbar navbar-ct-transparent" role="navigation-demo" id="demo-navbar">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
{#        <div class="navbar-header">#}
{#            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">#}
{#                <span class="sr-only">Toggle navigation</span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}
{#        </div>#}

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navigation-example-2">
            <ul class="nav navbar-nav navbar-right">
                <li>
            <a href="{% url 'app:index' %}" class="btn btn-danger">首页</a>
          </li>
                <li>
                    <a href="{% url 'app:add_one_xingming' %}" class="btn btn-danger">你的名字</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-->
</nav>


<div class="wrapper">
    <div class="demo-header demo-header-image" style="background-image: url('/static/assets/paper_img/add_name.jpeg');">
        <div class="motto">
        </div>
    </div>
    <div class="main">

            <div class="section landing-section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div align="center">
                            {% if msg %}
                                <a href="{% url 'app:get_one_info' the_xingming.id %}"><h2>{{ the_xingming.name }}已经存在,点击跳转</h2></a>
                            {% endif %}
                            </div>
                            <h2 class="text-center">添加你的名字</h2>
                            <form class="contact-form" action="" method="post">
                                 {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>姓氏</label>
                                        <input class="form-control" placeholder="请填写你的姓" name="xingshi">
                                    </div>
                                    <div class="col-md-6">
                                        <label>姓名</label>
                                        <input class="form-control" placeholder="请填写你的名字" name="xingming">
                                    </div>
                                </div>
                                  <br>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>五行</label>
                                        <input class="form-control" placeholder="可不填" name="five_elements">
                                    </div>

                                    <div class="col-md-6">
                                        <label>三才</label>
                                        <input class="form-control" placeholder="可不填" name="three_talents">
                                    </div>
                                </div>
                                <br>
                                <div align="center">
                                <input type="submit" name="" value="查询" class="input_submit btn btn-success" >
                                    </div>
                            </form>

                        </div>
                    </div>

                </div>
            </div>
        </div>


    <!-- </div> -->
    <div class="main">
        <div class="section section-nude section-with-space">
            <div class="container tim-container">
                <div class="row sharing-area text-center">
                    <h4><a href="http://www.fizzyi.com">欢迎来我的博客或者Github</a></h4>
                    <a href="https://github.com/Fizzyi" class="btn">
                        <i class="fa fa-github-square"></i>
                        Github
                    </a>
                    <a href="http://www.fizzyi.com" class="btn">
                        <i class="fa fa-rss-square"></i>
                        Fizzyi
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

<script src="/static/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="/static/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script src="/static/bootstrap3/js/bootstrap.js" type="text/javascript"></script>

<!--  Plugins -->
<script src="/static/assets/js/ct-paper-checkbox.js"></script>
<script src="/static/assets/js/ct-paper-radio.js"></script>
<script src="/static/assets/js/bootstrap-select.js"></script>
<script src="/static/assets/js/bootstrap-datepicker.js"></script>

<script src="/static/assets/js/ct-paper.js"></script>
</html>

baijiaxing/templates/tutorial.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<link rel="icon" type="image/png" href="/static/assets/paper_img/favicon.ico">
    
    <title>Paper Kit Tutorial by Creative Tim</title>
    
    <link href="/static/bootstrap3/css/bootstrap.css" rel="stylesheet" />
    <link href="/static/assets/css/ct-paper.css" rel="stylesheet"/>
    <link href="/static/assets/css/demo.css" rel="stylesheet" />
        
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
</head>
<body>

<nav class="navbar navbar-ct-danger" role="navigation-demo" id="demo-navbar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->


<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navigation-example-2">
      <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'app:index' %}" class="btn btn-danger">首页</a>
          </li>
          <li>
              <a href="{% url 'app:add_one_xingming' %}" class="btn btn-danger">你的名字</a>
          </li>
       </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>         
<div class="demo-header">
        <div class="motto">
            <h1 class="title-uppercase">{{ the_info.name }}</h1>
        </div>
</div>
<div class="main">
    <div class="section">
        <div class="container">
<!--         what is row -->
            <div class="row tim-row">
                <h2 class="text-center">很幸运，这个世界上至少有{{ the_info.the_same_people_number }}人和你同名同姓</h2>
                <legend></legend>
{#                <div class="col-md-8 col-md-offset-2">#}
{#                    <p>#}
{#                        <h3>同名同姓是一种缘分</h3>#}
{#                    </p>#}
{##}
{#                </div>#}

            </div>
<!--         end row -->
        
<!--         usage row -->
            <div class="row tim-row">
                <h2 class="text-center">{{ the_info.boy_ratio }}适用于男孩,{{ the_info.girl_ratio }}适用于女孩，</h2>
                <h2 class="text-center">那么你是帅哥还是美女？</h2>
                <legend></legend>
            </div>
<!--         end row -->  
        
<!--         file structure row -->
            <div class="row tim-row">
                <h2 class="text-center">姓名解析之五行为{{ the_info.five_elements }}</h2>
                <legend></legend>

            </div>
<!--         end row -->
            
<!--         restyled components row -->
            <div class="row tim-row">
                <h2 class="text-center">姓名解析之三才配置为{{ the_info.three_talents }}</h2>
                <legend></legend>

            </div>
<!--         end row -->
            

        </div>
<!-- end container -->
    </div>
</div>
<footer class="footer-demo section-dark">
    <div class="container">
         <div class="row sharing-area text-center">
                    <h4><a href="http://www.fizzyi.com">欢迎来我的博客或者Github</a></h4>
                    <a href="https://github.com/Fizzyi" class="btn">
                        <i class="fa fa-github-square"></i>
                        Github
                    </a>
                    <a href="http://www.fizzyi.com" class="btn">
                        <i class="fa fa-rss-square"></i>
                        Fizzyi
                    </a>
                </div>
    </div>
</footer>

</body>
<script src="/static/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="/static/assets/js/jquery-ui-1.10.4.custom.min.js" type="text/javascript"></script>

<script src="/static/bootstrap3/js/bootstrap.js" type="text/javascript"></script>

<!--  Plugins -->
<script src="/static/assets/js/ct-paper-checkbox.js"></script>
<script src="/static/assets/js/ct-paper-radio.js"></script>
<script src="/static/assets/js/bootstrap-select.js"></script>
<script src="/static/assets/js/bootstrap-datepicker.js"></script>

<script src="/static/assets/js/ct-paper.js"></script>
</html>